goCamp:
  url:
    search:
      campsite: http://apis.data.go.kr/B551011/GoCamping/basedList
      image: http://apis.data.go.kr/B551011/GoCamping/imageList
    serviceKey: p70pdHoxT%2Fy5tEkOpbp5jOLMkEYGV%2B8oND1YTMbzMCB9TvNN0cvX9tZSTnO0JV1W6BJk3z9Hq0FgrWDYTovevw%3D%3D

server:
  port: 8002

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/campinity
    username: root
    password: root

  redis:
    host: localhost
    port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG

