goCamp:
  url:
    search:
      campsite: http://apis.data.go.kr/B551011/GoCamping/basedList
      image: http://apis.data.go.kr/B551011/GoCamping/imageList
    serviceKey: p70pdHoxT%2Fy5tEkOpbp5jOLMkEYGV%2B8oND1YTMbzMCB9TvNN0cvX9tZSTnO0JV1W6BJk3z9Hq0FgrWDYTovevw%3D%3D

server:
  port: 8002

spring:
  batch-db:
    datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3306/batch
      username: root
      password: root
  campinity-db:
    datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3306/campinity
      username: root
      password: root

  redis:
    host: localhost
    port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  batch:
    job:
      enabled: false   # batch server 실행시켰을 때, 실행되는지 아닌지
    jdbc:
      isolation-level-for-create: default

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG


fcm:
  certification: /firebase/campinity-5aa0b-firebase-adminsdk-ap06a-54d2b91c8b.json
  url: https://fcm.googleapis.com/v1/projects/campinity-5aa0b/messages:send
  scope: https://www.googleapis.com/auth/cloud-platform
