version: "3.2"
services:
  database:
    container_name: database
    image: mariadb
    volumes:
      - type: volume
        source: initdb-volume
        target: /docker-entrypoint-initdb.d
      - type: volume
        source: confd-volume
        target: /etc/mysql/conf.d
      - type: volume
        source: data-volume
        target: /var/lib/mysql
    environment:
      - MYSQL_DATABASE_1=campinity
      - MYSQL_DATABASE_2=batch
      - MYSQL_ROOT_PASSWORD=ssafy1308!
    command: ['--character-set-server=utf8mb4',
              '--collation-server=utf8mb4_unicode_ci']
    ports:
      - 3306:3306
    restart: always

  application:
    build: ./demo-api-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://database:3306/campinity?useUnicode=true
      SPRING_DATASOURCE_USERNAME: server
      SPRING_DATASOURCE_PASSWORD: ssafy123!
    ports:
      - 8003:8003
    depends_on:
      - database
    volumes:
      - upload-images:/var/lib/images
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"

  batch-server:
    build: ./demo-batch-server
    environment:
      SPRING_BATCH_DB_DATASOURCE_URL: jdbc:mariadb://database:3306/batch?useUnicode=true
      SPRING_BATCH_DB_DATASOURCE_USERNAME: server
      SPRING_BATCH_DB_DATASOURCE_PASSWORD: ssafy123!
      SPRING_CAMPINITY_DB_DATASOURCE_URL: jdbc:mariadb://database:3306/campinity?useUnicode=true
      SPRING_CAMPINITY_DB_DATASOURCE_USERNAME: server
      SPRING_CAMPINITY_DATASOURCE_PASSWORD: ssafy123!
    ports:
      - 8002:8002
    depends_on:
      - database
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"

  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: redis_boot
    hostname: redis_boot
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379

volumes:
  upload-images:
  initdb-volume:
  confd-volume:
  data-volume:
