spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database:3306/campinity
    username: server
    password: ssafy123!

  redis:
    host: redis_boot
    port: 6379

  jpa:
    hibernate:
      ddl-auto: none